# Name:        build-container.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action will build and push a docker container, when triggered by
#              pushing a new git tag (that starts with the letter 'v').
name: Build Bashbot Containers
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Push Bashbot Container
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Set tag environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: mathewfleisch/bashbot:latest,mathewfleisch/bashbot:${{ env.RELEASE_VERSION }}
          cache-from: type=registry,ref=mathewfleisch/bashbot:latest
          cache-to: type=inline
      -
        name: Notify Release Channel
        env:
          SLACK_TOKEN: ${{ secrets.RELEASE_SLACK_TOKEN }}
          SLACK_CHANNEL: C02A1SH4GLT
        run: |
          arch=amd64
          [ $(uname -m) == "aarch64" ] && arch=arm64
          os=$(uname | tr '[:upper:]' '[:lower:]')
          wget -q https://github.com/mathew-fleisch/bashbot/releases/download/${{ env.RELEASE_VERSION }}/bashbot-${os}-${arch} -O bashbot
          chmod +x bashbot
          ./bashbot --version
          ./bashbot --slack-token ${{ secrets.SLACK_TOKEN }} --config-file .github/workflows/release-config.json --send-message-channel ${{ env.SLACK_CHANNEL }} --send-message-text "Bashbot <https://github.com/mathew-fleisch/bashbot/releases/tag/${{ env.RELEASE_VERSION}}|${{ env.RELEASE_VERSION }}> has been released!"